### ISSUE TITLE
Update `repo` in `IPFitting/Project.toml`

### ISSUE THREAD

**Issue by gelzinyte** [JuliaMolSim/MolSim#2]
The source repository for IPFitting is set to https://github.com/cortner/IPFitting.jl.git, which is a fork of a fork of https://github.com/ACEsuit/IPFitting.jl. Should that be updated in `IPFitting/Project.toml`?

**Comment by cortner** [comment]
yes probably. Thanks for pointing it out. 

(I think it is not a real problem as github remembers and redirects but still it should be fixed of course.)

**Comment by gelzinyte** [comment]
It's a bit of a problem, because the former is not up to date with the latter (v0.5.0 vs v0.10.0). While in most cases I can directly ask for v0.10.0, I ran in a bit of a more annoying problem with `dev IPFitting`, which was cloning v0.5.0 fork, but one of the installed packages was only compatible with the v0.10.0. I can still work around, but I think updating `repo` would solve all of this.

**Comment by cortner** [comment]
can this be closed?
